import os
from pathlib import Path

CELERY_LIVE_PREFIX = os.environ.get("CELERY_LIVE_PREFIX", "")


def env(key, default):
    return os.environ.get(f"{CELERY_LIVE_PREFIX}{key}", default)


WORKER_READINESS_FILE_LOCATION = env("WORKER_READINESS_FILE", "/tmp/worker-ready")
WORKER_READINESS_FILE = Path(WORKER_READINESS_FILE_LOCATION)

WORKER_LIVENESS_FILE_LOCATION = env("WORKER_LIVENESS_FILE", "/tmp/worker-live")
WORKER_LIVENESS_FILE = Path(WORKER_LIVENESS_FILE_LOCATION)
WORKER_LIVENESS_TIMEOUT = int(env("WORKER_LIVENESS_TIMEOUT", 60))

BEAT_READINESS_FILE_LOCATION = env("BEAT_READINESS_FILE", "/tmp/beat-ready")
BEAT_READINESS_FILE = Path(BEAT_READINESS_FILE_LOCATION)

BEAT_PID_FILE_LOCATION = env("BEAT_PI_FILE", "/tmp/celery-beat.pid")
BEAT_PID_FILE = Path(BEAT_PID_FILE_LOCATION)
